migrate(
  (app) => {
    // 1. produtos
    const produtos = new Collection({
      name: 'produtos',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        { name: 'codigo_item', type: 'text', required: true },
        { name: 'descricao_item', type: 'text' },
        { name: 'grupo_item', type: 'text' },
        { name: 'ativo', type: 'text' },
        { name: 'origem', type: 'text' },
        { name: 'data_carga', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: ['CREATE UNIQUE INDEX idx_produtos_codigo_item ON produtos (codigo_item)'],
    })
    app.save(produtos)

    // 2. racnew
    const racnew = new Collection({
      name: 'racnew',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        { name: 'tipo_documento', type: 'text' },
        { name: 'nf_entrega_futura', type: 'text' },
        { name: 'numero_sap', type: 'text' },
        { name: 'numero_nfe', type: 'text' },
        { name: 'data_lancamento', type: 'date' },
        { name: 'ultima_data_vencimento', type: 'date' },
        { name: 'docto_origem_destino', type: 'text' },
        { name: 'data_origem_destino', type: 'date' },
        { name: 'condicao_pagamento', type: 'text' },
        { name: 'codigo_cliente', type: 'text' },
        { name: 'nome_cliente', type: 'text' },
        { name: 'numero_linha', type: 'number' },
        { name: 'codigo_item', type: 'text' },
        { name: 'descricao_item', type: 'text' },
        { name: 'quantidade', type: 'number' },
        { name: 'qty_kg_lt', type: 'number' },
        { name: 'preco_item', type: 'number' },
        { name: 'desconto_linha', type: 'number' },
        { name: 'icms', type: 'number' },
        { name: 'pis', type: 'number' },
        { name: 'cofins', type: 'number' },
        { name: 'ipi', type: 'number' },
        { name: 'icms_partilha', type: 'number' },
        { name: 'total_linha', type: 'number' },
        { name: 'utilizacao', type: 'text' },
        { name: 'nome_vendedor', type: 'text' },
        { name: 'custo_item', type: 'number' },
        { name: 'nome_filial', type: 'text' },
        { name: 'conta', type: 'text' },
        { name: 'estado', type: 'text' },
        { name: 'cidade', type: 'text' },
        { name: 'origem', type: 'text' },
        { name: 'data_carga', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_racnew_unique ON racnew (numero_sap, numero_nfe, data_lancamento, codigo_cliente, codigo_item)',
        'CREATE INDEX idx_racnew_data_lancamento ON racnew (data_lancamento)',
        'CREATE INDEX idx_racnew_codigo_cliente ON racnew (codigo_cliente)',
        'CREATE INDEX idx_racnew_codigo_item ON racnew (codigo_item)',
        'CREATE INDEX idx_racnew_nome_vendedor ON racnew (nome_vendedor)',
      ],
    })
    app.save(racnew)

    // 3. netsales
    const netsales = new Collection({
      name: 'netsales',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        { name: 'tipo', type: 'text' },
        { name: 'codigo_cliente', type: 'text' },
        { name: 'nome_cliente', type: 'text' },
        { name: 'grupo_cliente', type: 'text' },
        { name: 'mercado', type: 'text' },
        { name: 'usuario_emissor', type: 'text' },
        { name: 'docdate', type: 'date' },
        { name: 'chave_documento', type: 'text' },
        { name: 'descrip', type: 'text' },
        { name: 'itms_grp_nam', type: 'text' },
        { name: 'codigo_item', type: 'text' },
        { name: 'numero_documento', type: 'text' },
        { name: 'quantidade', type: 'number' },
        { name: 'preco_unitario', type: 'number' },
        { name: 'valor_mercadoria', type: 'number' },
        { name: 'total_nf_sem_frete', type: 'number' },
        { name: 'total_nf_novo', type: 'number' },
        { name: 'valor_liquido', type: 'number' },
        { name: 'serial', type: 'text' },
        { name: 'custo_total', type: 'number' },
        { name: 'usage', type: 'text' },
        { name: 'classificacao', type: 'text' },
        { name: 'revenda', type: 'text' },
        { name: 'vendedor_revenda', type: 'text' },
        { name: 'municipio', type: 'text' },
        { name: 'estado', type: 'text' },
        { name: 'origem', type: 'text' },
        { name: 'data_carga', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_netsales_unique ON netsales (chave_documento, serial, docdate, codigo_cliente, codigo_item)',
        'CREATE INDEX idx_netsales_docdate ON netsales (docdate)',
        'CREATE INDEX idx_netsales_codigo_cliente ON netsales (codigo_cliente)',
        'CREATE INDEX idx_netsales_codigo_item ON netsales (codigo_item)',
      ],
    })
    app.save(netsales)

    // 4. vendas (consolidado)
    const vendas = new Collection({
      name: 'vendas',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        // RacNew fields
        { name: 'tipo_documento', type: 'text' },
        { name: 'nf_entrega_futura', type: 'text' },
        { name: 'numero_sap', type: 'text' },
        { name: 'numero_nfe', type: 'text' },
        { name: 'data_lancamento', type: 'date' },
        { name: 'ultima_data_vencimento', type: 'date' },
        { name: 'docto_origem_destino', type: 'text' },
        { name: 'data_origem_destino', type: 'date' },
        { name: 'condicao_pagamento', type: 'text' },
        { name: 'codigo_cliente', type: 'text' },
        { name: 'nome_cliente', type: 'text' },
        { name: 'numero_linha', type: 'number' },
        { name: 'codigo_item', type: 'text' },
        { name: 'descricao_item', type: 'text' },
        { name: 'quantidade', type: 'number' },
        { name: 'qty_kg_lt', type: 'number' },
        { name: 'preco_item', type: 'number' },
        { name: 'desconto_linha', type: 'number' },
        { name: 'icms', type: 'number' },
        { name: 'pis', type: 'number' },
        { name: 'cofins', type: 'number' },
        { name: 'ipi', type: 'number' },
        { name: 'icms_partilha', type: 'number' },
        { name: 'total_linha', type: 'number' },
        { name: 'utilizacao', type: 'text' },
        { name: 'nome_vendedor', type: 'text' },
        { name: 'custo_item', type: 'number' },
        { name: 'nome_filial', type: 'text' },
        { name: 'conta', type: 'text' },
        { name: 'estado', type: 'text' },
        { name: 'cidade', type: 'text' },
        // 12 exclusive NetSales fields
        { name: 'grupo_cliente', type: 'text' },
        { name: 'mercado', type: 'text' },
        { name: 'usuario_emissor_pedido', type: 'text' },
        { name: 'itms_grp_nam', type: 'text' },
        { name: 'numero_documento_netsales', type: 'text' },
        { name: 'preco_unitario', type: 'number' },
        { name: 'total_nf_sem_frete', type: 'number' },
        { name: 'total_nf_novo', type: 'number' },
        { name: 'valor_liquido', type: 'number' },
        { name: 'custo_total', type: 'number' },
        { name: 'classificacao', type: 'text' },
        { name: 'vendedor_revenda', type: 'text' },
        // Enriched fields
        { name: 'grupo_item', type: 'text' },
        { name: 'vendedor_cliente', type: 'text' },
        // Metadata
        { name: 'origem', type: 'text' },
        { name: 'data_carga', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_vendas_vendedor_cliente ON vendas (vendedor_cliente)',
        'CREATE INDEX idx_vendas_nome_vendedor ON vendas (nome_vendedor)',
        'CREATE INDEX idx_vendas_grupo_item ON vendas (grupo_item)',
        'CREATE INDEX idx_vendas_data_lancamento ON vendas (data_lancamento)',
        'CREATE INDEX idx_vendas_estado ON vendas (estado)',
        'CREATE INDEX idx_vendas_cidade ON vendas (cidade)',
        'CREATE INDEX idx_vendas_utilizacao ON vendas (utilizacao)',
        'CREATE INDEX idx_vendas_numero_nfe ON vendas (numero_nfe)',
      ],
    })
    app.save(vendas)
  },
  (app) => {
    const v = app.findCollectionByNameOrId('vendas')
    if (v) app.delete(v)
    const n = app.findCollectionByNameOrId('netsales')
    if (n) app.delete(n)
    const r = app.findCollectionByNameOrId('racnew')
    if (r) app.delete(r)
    const p = app.findCollectionByNameOrId('produtos')
    if (p) app.delete(p)
  },
)
